<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>EchoResonance</RootNamespace>
    <AssemblyName>EchoResonance</AssemblyName>
    <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
